# Generated by Django 5.2.14 on 2026-05-20 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('forecast_days', models.PositiveIntegerField(default=7)),
                ('total_predictions', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forecast Run',
                'verbose_name_plural': 'Forecast Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_views', models.PositiveIntegerField(default=0)),
                ('lower_bound', models.PositiveIntegerField(default=0)),
                ('upper_bound', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(default='ARIMA', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='analytics.category')),
                ('forecast_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='analytics.forecastrun')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['prediction_date'],
                'indexes': [models.Index(fields=['prediction_date'], name='analytics_p_predict_42f9ec_idx'), models.Index(fields=['category', 'prediction_date'], name='analytics_p_categor_925d8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_path', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='analytics.category')),
            ],
            options={
                'verbose_name': 'Traffic Data',
                'verbose_name_plural': 'Traffic Data',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='analytics_t_date_6cba16_idx'), models.Index(fields=['category', 'date'], name='analytics_t_categor_35317c_idx')],
            },
        ),
    ]
